version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  elastalert:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    cap_add:
      - SYS_TIME
      - SYS_NICE
    volumes:
      - ./src:/opt/elastalert-server/src
      - ./package.json:/opt/elastalert-server/package.json
      - ./logs:/opt/elastalert/logs
      - ./rules:/opt/elastalert/rules
      - ./config:/opt/elastalert/config
    links:
      - elasticsearch:elasticsearch
        # environment:
        #     - ELASTICSEARCH_USER=elastic
        #     - ELASTICSEARCH_PASSWORD=changeme
        #     - SET_CONTAINER_TIMEZONE=true
    ports:
      - "3030:3030"
